### ISSUE TITLE
Multiple DNS requests for test-{randomstring}.null-addr.net

### ISSUE THREAD

**Issue by futurealecks** [brianshea2/addr.tools#10]
Hello, first thanks for running this project. 

As of the first of November our threat detection system flags `test-{randomstring}.null-addr.net` as a threat. Visiting the page will kick off 30+ requests to these domains (null-addr.biz, null-addr.info, etc.). Curious what that is used for?

**Comment by futurealecks** [comment]
Answered my own question 👍 

https://github.com/brianshea2/addr.tools/blob/f39c4bfb6bd5a58876fe88143336913e4d794416/website/dnscheck.tools/main.js#L387

**Comment by brianshea2** [comment]
Curious why they're triggering your threat detection? I've set up those domains to always resolve to 0.0.0.0 (or :: for ipv6), the same as how most filtering DNS services resolve a "blocked" domain. Maybe it's due to the newness of those domains (just being registered)? Either way, can confirm these domains are expected and used to determine the average resolution speed shown in the bottom left of the site.
