### ISSUE TITLE
Public Suffix List

### ISSUE THREAD

**Issue by bwbroersma** [brianshea2/addr.tools#2]
I did not see any addr.tools on the [Public Suffic List](https://github.com/publicsuffix/list?tab=readme-ov-file#the-public-suffix-list).

For the dynamic and IPv6 it seems logical to put `dyn.addr.tools` and `ip.addr.tools` on the Public Suffix List, so an IPv6 can only set cookies on `ipv6.ip.addr.tools` and not for `ip.addr.tools` or higher. For IPv4 this is tricky, since wildcards are allowed, but only one, so `*.*.*.ip.addr.tools` is an invalid [format](https://github.com/publicsuffix/list/wiki/Format#entry-specification).

```none
// addr.tools: https://www.addr.tools/
dyn.addr.tools
ip.addr.tools
````
1. deny `hash.dyn.addr.tools` to set cookies for `dyn.addr.tools` or above
2. deny `ipv6.ip.addr.tools` to set `ip.addr.tools` or above

It would be benefitial from a security point of view to also use a hyphen for joining of the IPv4 address to the label.

**Comment by brianshea2** [comment]
Indeed those are public suffixes. I had a PR open with the PSL for adding the `myaddr.{tools,dev,io}` domains, which are clearly public suffixes and have more users than the ones you mentioned, but was ultimately denied inclusion due to not having enough "affected users". The PSL is run by a bunch of volunteers, and to be honest, the whole experience of submitting a PR, waiting several months for anyone to look at it, then to be denied because these services aren't one of the "big ones" left a bad taste in my mouth. I may try again in the future.

**Comment by brianshea2** [comment]
Some previous discussion here: https://www.reddit.com/r/dns/comments/17tuscu/comment/k90lndp/

Rejected PSL PR here: https://github.com/publicsuffix/list/pull/1912

**Comment by brianshea2** [comment]
The domains used for dynamic dns services have been accepted into the PSL!

https://github.com/publicsuffix/list/pull/2320
